# Generated by Django 4.0.8 on 2023-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_entreprise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='addresse',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
